# Options specific to a GOV.UK environment
integration: -t "not @pending" -t "not @notintegration"
staging: -t "not @pending" -t "not @notstaging"
production: -t "not @pending" -t "not @notproduction"
